// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spotly.API.Data;

#nullable disable

namespace Spotly.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413192927_CleanStart")]
    partial class CleanStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Spotly.API.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GourmetScore")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhotoScore")
                        .HasColumnType("integer");

                    b.Property<int>("TouristScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tarihi/Manzara",
                            Description = "Şehrin simgesi, 360 derece manzara.",
                            GourmetScore = 30,
                            ImageUrl = "galata.jpg",
                            Latitude = 41.025599999999997,
                            Longitude = 28.9741,
                            Name = "Galata Kulesi",
                            PhotoScore = 100,
                            TouristScore = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mimari/Fotoğraf",
                            Description = "Art Nouveau tarzı kıvrımlı tarihi merdivenler.",
                            GourmetScore = 0,
                            ImageUrl = "kamondo.jpg",
                            Latitude = 41.023800000000001,
                            Longitude = 28.9739,
                            Name = "Kamondo Merdivenleri",
                            PhotoScore = 95,
                            TouristScore = 60
                        },
                        new
                        {
                            Id = 3,
                            Category = "Kafe/Gurme",
                            Description = "Galata Meydanı'nda şık ve lezzetli tatlılar.",
                            GourmetScore = 80,
                            ImageUrl = "sirinfirin.jpg",
                            Latitude = 41.024999999999999,
                            Longitude = 28.974499999999999,
                            Name = "Şirin Fırın",
                            PhotoScore = 75,
                            TouristScore = 50
                        },
                        new
                        {
                            Id = 12,
                            Category = "Kültür/Mimari",
                            Description = "Eski Osmanlı Bankası, muazzam mimari ve kütüphane.",
                            GourmetScore = 20,
                            ImageUrl = "saltgalata.jpg",
                            Latitude = 41.023200000000003,
                            Longitude = 28.9739,
                            Name = "Salt Galata",
                            PhotoScore = 95,
                            TouristScore = 70
                        },
                        new
                        {
                            Id = 13,
                            Category = "Üst Düzey Gurme",
                            Description = "Michelin yıldızlı, modern Türk mutfağı ve muazzam manzara.",
                            GourmetScore = 100,
                            ImageUrl = "neolokal.jpg",
                            Latitude = 41.023499999999999,
                            Longitude = 28.973299999999998,
                            Name = "Neolokal",
                            PhotoScore = 85,
                            TouristScore = 60
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gurme",
                            Description = "İstanbul'un en meşhur baklavacısı.",
                            GourmetScore = 100,
                            ImageUrl = "gulluoglu.jpg",
                            Latitude = 41.0227,
                            Longitude = 28.977399999999999,
                            Name = "Karaköy Güllüoğlu",
                            PhotoScore = 40,
                            TouristScore = 85
                        },
                        new
                        {
                            Id = 5,
                            Category = "Kafe/Fotoğraf",
                            Description = "Asma yaprakları altında salaş ve estetik kahveci.",
                            GourmetScore = 75,
                            ImageUrl = "karabatak.jpg",
                            Latitude = 41.023400000000002,
                            Longitude = 28.9785,
                            Name = "Karabatak Kafe",
                            PhotoScore = 90,
                            TouristScore = 50
                        },
                        new
                        {
                            Id = 6,
                            Category = "Mimari/Fotoğraf",
                            Description = "Tarihi dokusu bozulmamış şık bir sokak.",
                            GourmetScore = 40,
                            ImageUrl = "fransizgecidi.jpg",
                            Latitude = 41.023000000000003,
                            Longitude = 28.977,
                            Name = "Fransız Geçidi",
                            PhotoScore = 85,
                            TouristScore = 60
                        },
                        new
                        {
                            Id = 7,
                            Category = "Modern/Manzara",
                            Description = "Modern mimari, boğaz manzarası ve lüks restoranlar.",
                            GourmetScore = 80,
                            ImageUrl = "galataport.jpg",
                            Latitude = 41.024999999999999,
                            Longitude = 28.981000000000002,
                            Name = "Galataport Sahil",
                            PhotoScore = 85,
                            TouristScore = 90
                        },
                        new
                        {
                            Id = 8,
                            Category = "Tarihi/Alışveriş",
                            Description = "Baharat kokulu, renkli, otantik bir pazar.",
                            GourmetScore = 70,
                            ImageUrl = "misircarsisi.jpg",
                            Latitude = 41.016500000000001,
                            Longitude = 28.970500000000001,
                            Name = "Mısır Çarşısı",
                            PhotoScore = 90,
                            TouristScore = 95
                        },
                        new
                        {
                            Id = 9,
                            Category = "Gurme/Sokak Lezzeti",
                            Description = "Sallanan teknelerde geleneksel balık ekmek.",
                            GourmetScore = 85,
                            ImageUrl = "balikekmek.jpg",
                            Latitude = 41.018000000000001,
                            Longitude = 28.972000000000001,
                            Name = "Eminönü Tarihi Balıkçısı",
                            PhotoScore = 75,
                            TouristScore = 80
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tarihi/Dini",
                            Description = "Eminönü silüetinin ayrılmaz, görkemli parçası.",
                            GourmetScore = 0,
                            ImageUrl = "yenicami.jpg",
                            Latitude = 41.016800000000003,
                            Longitude = 28.971499999999999,
                            Name = "Yeni Cami",
                            PhotoScore = 85,
                            TouristScore = 90
                        },
                        new
                        {
                            Id = 11,
                            Category = "Gurme",
                            Description = "Lokum ve şerbetli tatlılarda tarihi bir marka.",
                            GourmetScore = 95,
                            ImageUrl = "hafizmustafa.jpg",
                            Latitude = 41.014499999999998,
                            Longitude = 28.975000000000001,
                            Name = "Hafız Mustafa 1864",
                            PhotoScore = 60,
                            TouristScore = 85
                        },
                        new
                        {
                            Id = 14,
                            Category = "Tarihi/Sanat",
                            Description = "Eminönü kalabalığından gizlenmiş, İznik çinileriyle meşhur şaheser.",
                            GourmetScore = 0,
                            ImageUrl = "rustempasa.jpg",
                            Latitude = 41.017800000000001,
                            Longitude = 28.968800000000002,
                            Name = "Rüstem Paşa Camii",
                            PhotoScore = 95,
                            TouristScore = 75
                        },
                        new
                        {
                            Id = 15,
                            Category = "Tarihi/Mimari",
                            Description = "Orient Express'in son durağı, tarihi ve nostaljik atmosfer.",
                            GourmetScore = 10,
                            ImageUrl = "sirkecigari.jpg",
                            Latitude = 41.015300000000003,
                            Longitude = 28.9772,
                            Name = "Sirkeci Garı",
                            PhotoScore = 80,
                            TouristScore = 85
                        },
                        new
                        {
                            Id = 16,
                            Category = "Gurme/Esnaf",
                            Description = "Döner, pide ve esnaf lokantalarının tarihi sokağı.",
                            GourmetScore = 95,
                            ImageUrl = "hocapasa.jpg",
                            Latitude = 41.013500000000001,
                            Longitude = 28.977499999999999,
                            Name = "Tarihi Hocapaşa Lokantaları",
                            PhotoScore = 50,
                            TouristScore = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
